from __future__ import annotations

from pathlib import Path
from xml.etree import ElementTree as ET

import pytest

from src.agents.nodes.convert_xosc_node import (
    DETERMINISTIC_XOSC_DATE,
    MANEUVER_BUILDERS,
    SPECIAL_BUILDERS,
    ConversionError,
    _lane_change,
    convert_spec_to_xosc,
    convert_xosc_node,
)
from src.models.schemas import (
    ActorSpec,
    ActorType,
    IssueCode,
    ManeuverSpec,
    ManeuverType,
    ODDCell,
    Position,
    RoadType,
    ScenarioSpec,
    TimeOfDay,
    TriggerCondition,
    VehicleCategory,
    Weather,
)
from src.services.scenario import templates
from src.services.scenario.templates import get_template

ROOT = Path(__file__).parents[2]
GOLDENS = ROOT / "fixtures" / "xosc" / "generated"
SUPPORTED_MANEUVERS = (
    ManeuverType.CUT_IN,
    ManeuverType.SUDDEN_BRAKE,
    ManeuverType.RUN_RED_LIGHT,
    ManeuverType.JAYWALK,
    ManeuverType.WRONG_WAY,
    ManeuverType.LANE_DRIFT,
    ManeuverType.STOP_IN_LANE,
)


def make_spec(
    maneuver: ManeuverType,
    *,
    trigger_type: str = "simulation_time",
    title: str = "Generated scenario",
) -> ScenarioSpec:
    pedestrian = maneuver is ManeuverType.JAYWALK
    category = VehicleCategory.PEDESTRIAN if pedestrian else VehicleCategory.CAR
    actor_type = ActorType.PEDESTRIAN if pedestrian else ActorType.CAR
    is_cut_in = maneuver is ManeuverType.CUT_IN
    is_lane_drift = maneuver is ManeuverType.LANE_DRIFT
    actor_s_offset = -25 if is_cut_in else (-15 if is_lane_drift else 20)
    actor_speed = 50 if is_cut_in else (40 if is_lane_drift else (0 if pedestrian else 20))
    # cut_in phải bắn SAU lúc hai xe đi ngang nhau (25 m / 5,56 m/s = 4,5 s), nếu
    # không adversary nhập làn ở sau lưng ego rồi tông đuôi — đo được trên CARLA
    # 22/08 với trigger 2,0: va chạm lúc adversary còn sau ego 4,56 m.
    # Xem `cut_in_trigger_before_overtake`.
    trigger_value = 6 if is_cut_in else (5 if is_lane_drift else 2)
    target_speed = (
        20
        if is_cut_in
        else (0 if maneuver in {ManeuverType.SUDDEN_BRAKE, ManeuverType.STOP_IN_LANE} else (5 if pedestrian else 10))
    )
    return ScenarioSpec(
        scenario_id="sc_900",
        description_vi="fixture generated by converter tests",
        title=title,
        odd=ODDCell(
            road_type=RoadType.HIGHWAY,
            weather=Weather.CLEAR,
            actor_type=actor_type,
            maneuver=maneuver,
        ),
        time_of_day=TimeOfDay.DAY,
        actors=[
            ActorSpec(
                name="hero",
                category=VehicleCategory.CAR,
                position=Position(lane_offset=0, s_offset_m=0),
                initial_speed_kmh=30,
                is_ego=True,
            ),
            ActorSpec(
                name="other",
                category=category,
                position=Position(lane_offset=-1, s_offset_m=actor_s_offset),
                initial_speed_kmh=actor_speed,
                is_ego=False,
            ),
        ],
        maneuvers=[
            ManeuverSpec(
                actor_name="other",
                maneuver=maneuver,
                trigger=TriggerCondition(type=trigger_type, value=trigger_value),
                target_speed_kmh=target_speed,
            )
        ],
        duration_s=30,
    )


@pytest.mark.parametrize("maneuver", SUPPORTED_MANEUVERS)
def test_each_maneuver_matches_byte_identical_golden(maneuver: ManeuverType) -> None:
    xml = convert_spec_to_xosc(make_spec(maneuver))
    assert xml == convert_spec_to_xosc(make_spec(maneuver))
    assert xml.encode() == (GOLDENS / f"{maneuver.value}.xosc").read_bytes()
    ET.fromstring(xml)


def test_act_closes_on_collision_as_well_as_on_timeout() -> None:
    """Mọi thứ sau va chạm đầu tiên là dữ liệu bỏ đi — mô phỏng tiếp chỉ đốt GPU.

    `sc_001` chạm ở giây 11,3 rồi chạy thêm 19 giây, và `trajectory.summarise` cắt
    hết phần đó (không cắt thì `adversary_lane_deviation_m` đọc ra 21,18 m thay vì
    1,689 m vì xe bị hất khỏi làn).

    Hai điều kiện phải nằm ở HAI `ConditionGroup` khác nhau: trigger trong
    OpenSCENARIO là OR giữa các nhóm và AND bên trong một nhóm — gộp chung là
    thành "hết giờ VÀ có va chạm", tức là không bao giờ đóng sớm.
    """
    root = ET.fromstring(convert_spec_to_xosc(make_spec(ManeuverType.CUT_IN)))
    stop = root.find(".//Act/StopTrigger")
    assert stop is not None
    groups = stop.findall("ConditionGroup")
    assert len(groups) == 2, "hết giờ và va chạm phải là hai nhánh OR"
    assert groups[0].find(".//SimulationTimeCondition") is not None
    collision = groups[1].find(".//CollisionCondition/EntityRef")
    assert collision is not None and collision.get("entityRef") == "other"


def test_builder_catalog_covers_all_maneuver_types() -> None:
    assert set(MANEUVER_BUILDERS) | set(SPECIAL_BUILDERS) == set(ManeuverType)
    assert set(MANEUVER_BUILDERS).isdisjoint(SPECIAL_BUILDERS)


def test_semantic_spec_does_not_expose_carla_or_xosc_placement_fields() -> None:
    simulator_fields = {
        "blueprint",
        "carla_map",
        "map_name",
        "road_id",
        "lane_id",
        "world_position",
        "x",
        "y",
        "z",
        "h",
    }
    for model in (ScenarioSpec, ActorSpec, Position, ManeuverSpec):
        assert simulator_fields.isdisjoint(model.model_fields)


@pytest.mark.asyncio
async def test_unverified_road_type_returns_catalog_error() -> None:
    data = make_spec(ManeuverType.SUDDEN_BRAKE).model_dump()
    data["odd"]["road_type"] = RoadType.INTERSECTION
    result = await convert_xosc_node({"spec": ScenarioSpec.model_validate(data)})
    assert result["issues"][0].code is IssueCode.TEMPLATE_CATALOG_INCONSISTENT


def test_relative_positions_follow_adr_012() -> None:
    root = ET.fromstring(convert_spec_to_xosc(make_spec(ManeuverType.CUT_IN)))
    ego = root.find(".//Private[@entityRef='hero']//WorldPosition")
    other = root.find(".//Private[@entityRef='other']//RelativeLanePosition")
    lane_change = root.find(".//LaneChangeActionDynamics")
    target = root.find(".//RelativeTargetLane")
    assert ego is not None
    assert other is not None and other.attrib == {"entityRef": "hero", "dLane": "1", "ds": "-25", "offset": "0"}
    assert lane_change is not None and lane_change.get("dynamicsDimension") == "distance"
    assert target is not None and target.get("value") != "0"


def test_generated_xml_contains_verified_fixture_runtime_blocks() -> None:
    root = ET.fromstring(convert_spec_to_xosc(make_spec(ManeuverType.CUT_IN)))
    assert root.find(".//Init/Actions/GlobalAction/EnvironmentAction/Environment") is not None
    assert root.find(".//Private[@entityRef='hero']//WorldPosition") is not None
    assert root.find(".//Private[@entityRef='other']//RelativeLanePosition") is not None
    assert root.find(".//Event[@name='event_0_brake_after_cut_in']//SpeedAction") is not None
    slowdown_trigger = root.find(".//Event[@name='event_0_brake_after_cut_in']//StoryboardElementStateCondition")
    assert slowdown_trigger is not None and slowdown_trigger.attrib == {
        "storyboardElementType": "event",
        "storyboardElementRef": "event_0_cut_in",
        "state": "completeState",
    }
    assert root.find(".//Event[@name='event_0_brake_after_cut_in']//SimulationTimeCondition") is None
    criteria = {item.get("name") for item in root.findall("./Storyboard/StopTrigger/ConditionGroup/Condition")}
    assert criteria == {
        "criteria_CollisionTest",
        "criteria_DrivenDistanceTest",
        "criteria_MaxVelocityTest",
    }


def test_lane_change_direction_returns_actor_to_ego_lane() -> None:
    left = ET.fromstring(convert_spec_to_xosc(make_spec(ManeuverType.CUT_IN)))
    assert left.find(".//RelativeTargetLane").get("value") == "-1"
    data = make_spec(ManeuverType.CUT_IN).model_dump()
    data["actors"][1]["position"]["lane_offset"] = 2
    right = ET.fromstring(convert_spec_to_xosc(ScenarioSpec.model_validate(data)))
    assert right.find(".//RelativeTargetLane").get("value") == "2"


def test_lane_change_rejects_zero_at_the_builder_boundary() -> None:
    parent = ET.Element("PrivateAction")
    with pytest.raises(ConversionError, match="value=0 crashes"):
        _lane_change(parent, slow=False, lane_change_value=0)
    assert len(parent) == 0


def test_lane_drift_uses_partial_offset_not_full_lane_change() -> None:
    root = ET.fromstring(convert_spec_to_xosc(make_spec(ManeuverType.LANE_DRIFT)))
    assert root.find(".//LaneOffsetAction") is not None
    assert root.find(".//LaneOffsetAction/../LaneChangeAction") is None
    # Actor đứng bên TRÁI ego (lane_offset = -1) phải lấn sang PHẢI để về phía
    # ego. ScenarioRunner đọc dương = sang phải (atomic_behaviors.py:1122), ngược
    # với quy ước OpenSCENARIO — nên giá trị đúng là +0.7, không phải -0.7.
    assert root.find(".//AbsoluteTargetLaneOffset").get("value") == "0.7"
    criteria = {item.get("name") for item in root.findall("./Storyboard/StopTrigger/ConditionGroup/Condition")}
    assert "criteria_KeepLaneTest" in criteria
    ego_speed = root.find(".//Private[@entityRef='hero']//AbsoluteTargetSpeed")
    actor_speed = root.find(".//Private[@entityRef='other']//AbsoluteTargetSpeed")
    actor_position = root.find(".//Private[@entityRef='other']//RelativeLanePosition")
    trigger = root.find(".//Event[@name='event_0_lane_drift']//SimulationTimeCondition")
    assert ego_speed is not None and ego_speed.get("value") == "8.333333"
    assert actor_speed is not None and actor_speed.get("value") == "11.111111"
    assert actor_position is not None and actor_position.get("ds") == "-15"
    assert trigger is not None and trigger.get("value") == "5"


def test_run_red_light_keeps_actor_moving_and_adds_criterion() -> None:
    root = ET.fromstring(convert_spec_to_xosc(make_spec(ManeuverType.RUN_RED_LIGHT)))
    speed = root.find(".//Event[@name='event_0_run_red_light']//AbsoluteTargetSpeed")
    criteria = {item.get("name") for item in root.findall("./Storyboard/StopTrigger/ConditionGroup/Condition")}
    assert speed is not None and float(speed.get("value")) > 0
    assert "criteria_RunningRedLightTest" in criteria


def test_jaywalk_uses_supported_pedestrian_routing_action() -> None:
    root = ET.fromstring(convert_spec_to_xosc(make_spec(ManeuverType.JAYWALK)))
    pedestrian = root.find(".//ScenarioObject[@name='other']/Pedestrian")
    acquire = root.find(".//Event[@name='event_0_jaywalk']//AcquirePositionAction")
    target = root.find(".//Event[@name='event_0_jaywalk']//AcquirePositionAction/Position/RelativeLanePosition")
    assert pedestrian is not None
    assert acquire is not None
    assert target is not None and target.get("dLane") == "-1"


def test_wrong_way_rotates_actor_and_adds_criterion() -> None:
    root = ET.fromstring(convert_spec_to_xosc(make_spec(ManeuverType.WRONG_WAY)))
    orientation = root.find(".//Event[@name='event_0_wrong_way']//RelativeLanePosition/Orientation")
    criteria = {item.get("name") for item in root.findall("./Storyboard/StopTrigger/ConditionGroup/Condition")}
    assert orientation is not None and orientation.attrib == {
        "h": "3.141593",
        "p": "0",
        "r": "0",
        "type": "relative",
    }
    assert "criteria_WrongLaneTest" in criteria


@pytest.mark.parametrize("maneuver", SUPPORTED_MANEUVERS)
def test_every_maneuver_group_stays_open_until_duration(maneuver: ManeuverType) -> None:
    """Mỗi maneuver group phải có event giữ kịch bản chạy hết ``duration_s``.

    ScenarioRunner dựng Act là ``Parallel(SUCCESS_ON_ONE, [Maneuvers, EndConditions])``
    (`srunner/scenarios/open_scenario.py`), nên ``StopTrigger`` của Act là nhánh
    OR chứ không phải sàn thời gian — hết việc trong storyboard là kịch bản đóng
    ngay lập tức.

    Đo trên CARLA ngày 22/08 trước khi có event này: `stop_in_lane`,
    `run_red_light`, `jaywalk` và `wrong_way` đều kết thúc sau ~2,6 s với ego mới
    đi 16,6 m — chưa kịp tới chỗ adversary, nên không kịch bản nào trong bốn cái
    đó mô phỏng được gì. Sau khi có: cả bốn chạy đủ 30,5 s, và `wrong_way` dựng
    được va chạm thật.

    Test này tách khỏi golden byte-identical có chủ đích: golden bắt được *thay
    đổi*, còn test này nói *vì sao* file phải như thế. Xoá `_add_hold_open_event`
    rồi sinh lại golden thì golden vẫn xanh — chỉ test này đỏ.
    """
    spec = make_spec(maneuver)
    root = ET.fromstring(convert_spec_to_xosc(spec))
    groups = root.findall("./Storyboard/Story/Act/ManeuverGroup")
    assert groups, "Act phải có ít nhất một ManeuverGroup"
    for group in groups:
        held_open = [
            condition
            for condition in group.findall(".//Event/StartTrigger//SimulationTimeCondition")
            if float(condition.get("value")) == pytest.approx(spec.duration_s)
            and condition.get("rule") == "greaterThan"
        ]
        assert held_open, (
            f"{group.get('name')} không có event nào chờ tới duration_s={spec.duration_s}; "
            "kịch bản sẽ đóng ngay khi adversary xong việc"
        )


def test_fixed_dates_are_named_deterministic_output() -> None:
    root = ET.fromstring(convert_spec_to_xosc(make_spec(ManeuverType.SUDDEN_BRAKE)))
    assert root.find("FileHeader").get("date") == f"{DETERMINISTIC_XOSC_DATE}T00:00:00"
    assert root.find(".//Environment/TimeOfDay").get("dateTime") == f"{DETERMINISTIC_XOSC_DATE}T12:00:00"


@pytest.mark.parametrize("maneuver", SUPPORTED_MANEUVERS)
def test_criterion_arguments_match_scenario_runner_0_9_15_contract(maneuver: ManeuverType) -> None:
    root = ET.fromstring(convert_spec_to_xosc(make_spec(maneuver)))
    declarations = {
        item.get("name"): item.get("value") for item in root.findall("./ParameterDeclarations/ParameterDeclaration")
    }
    conditions = {
        condition.get("name"): condition.find("./ByValueCondition/ParameterCondition")
        for condition in root.findall("./Storyboard/StopTrigger/ConditionGroup/Condition")
    }
    assert declarations == {"distance_success": "50", "max_velocity_allowed": "30"}
    for name, parameter in conditions.items():
        assert parameter is not None
        parameter_ref = parameter.get("parameterRef")
        value = parameter.get("value")
        if name in {"criteria_DrivenDistanceTest", "criteria_MaxVelocityTest"}:
            assert parameter_ref in declarations
            assert value not in {None, ""}
        else:
            assert (parameter_ref, value) == ("", "")


@pytest.mark.parametrize(
    ("trigger_type", "xpath"),
    [
        ("distance_to_ego", ".//RelativeDistanceCondition"),
        ("simulation_time", ".//Event/StartTrigger//SimulationTimeCondition"),
    ],
)
def test_both_trigger_types_map_correctly(trigger_type: str, xpath: str) -> None:
    root = ET.fromstring(convert_spec_to_xosc(make_spec(ManeuverType.SUDDEN_BRAKE, trigger_type=trigger_type)))
    trigger = root.find(xpath)
    assert trigger is not None and trigger.get("value") == "2"


def test_actor_controlled_xml_attributes_are_escaped() -> None:
    spec = make_spec(ManeuverType.SUDDEN_BRAKE, title='A & B "quoted" <title>')
    data = spec.model_dump()
    data["actors"][1]["name"] = 'other & "quoted"'
    data["maneuvers"][0]["actor_name"] = 'other & "quoted"'
    xml = convert_spec_to_xosc(ScenarioSpec.model_validate(data))
    assert xml.startswith("<?xml version='1.0' encoding='UTF-8'?>\n")
    assert "&amp;" in xml and "&quot;" in xml and "&lt;title&gt;" in xml
    ET.fromstring(xml)


def test_non_hero_ego_is_rejected_instead_of_generating_broken_references() -> None:
    data = make_spec(ManeuverType.SUDDEN_BRAKE).model_dump()
    data["actors"][0]["name"] = "ego"
    with pytest.raises(Exception, match="named 'hero'"):
        convert_spec_to_xosc(ScenarioSpec.model_validate(data))


@pytest.mark.asyncio
async def test_catalog_mismatch_returns_terminal_issue(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.delitem(MANEUVER_BUILDERS, ManeuverType.SUDDEN_BRAKE)
    result = await convert_xosc_node({"spec": make_spec(ManeuverType.SUDDEN_BRAKE)})
    assert result["issues"][0].code is IssueCode.TEMPLATE_CATALOG_INCONSISTENT
    assert result["issues"][0].repairable_by_llm is False
    assert result["failed_reason"]
    assert "xosc_content" not in result


@pytest.mark.asyncio
async def test_invalid_cut_in_semantics_fail_conversion() -> None:
    data = make_spec(ManeuverType.CUT_IN).model_dump()
    data["maneuvers"][0]["trigger"]["type"] = "distance_to_ego"
    result = await convert_xosc_node({"spec": ScenarioSpec.model_validate(data)})
    assert result["issues"][0].code is IssueCode.CONVERTER_ERROR
    assert result["issues"][0].repairable_by_llm is False
    assert result["failed_reason"]
    assert "xosc_content" not in result


@pytest.mark.asyncio
async def test_unexpected_converter_error_is_terminal(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(templates, "TEMPLATE_CATALOG", None)
    result = await convert_xosc_node({"spec": make_spec(ManeuverType.CUT_IN)})
    assert result["issues"][0].code is IssueCode.CONVERTER_ERROR
    assert "xosc_content" not in result


def test_generated_fixtures_validate_against_openscenario_1_xsd() -> None:
    import xmlschema

    fixtures = sorted(GOLDENS.glob("*.xosc"))
    assert {fixture.stem for fixture in fixtures} == {maneuver.value for maneuver in SUPPORTED_MANEUVERS}
    schema = xmlschema.XMLSchema(ROOT / "tests" / "schemas" / "OpenSCENARIO_1_0.xsd")
    for fixture in fixtures:
        schema.validate(fixture)


def test_actor_beyond_the_anchor_reach_is_rejected_before_carla_sees_it() -> None:
    """Anchor chỉ phủ được một đoạn đường; ra ngoài đó ScenarioRunner không spawn nổi.

    `Position.s_offset_m` cho phép ±200 vì đó là biên kiểu dữ liệu. Biên thật là
    của anchor: đo trên CARLA 22/08, làn giữ nguyên định danh tới +40 m về phía
    trước và ít nhất −120 m về phía sau. Hai kịch bản `wrong_way` đặt actor ở
    +120 m đều chết bằng `Error: Unable to add actors` — thông báo không nhắc gì
    tới khoảng cách, nên chặn sớm là cách duy nhất để người sinh kịch bản hiểu.
    """
    data = make_spec(ManeuverType.SUDDEN_BRAKE).model_dump()
    data["actors"][1]["position"]["s_offset_m"] = 120.0

    with pytest.raises(ConversionError, match="ngoài đoạn đường"):
        convert_spec_to_xosc(ScenarioSpec.model_validate(data))


def test_actor_inside_the_anchor_reach_still_converts() -> None:
    """Biên là biên của anchor, không phải lệnh cấm mọi khoảng cách lớn."""
    data = make_spec(ManeuverType.SUDDEN_BRAKE).model_dump()
    data["actors"][1]["position"]["s_offset_m"] = 35.0
    assert convert_spec_to_xosc(ScenarioSpec.model_validate(data)).startswith("<?xml")


def test_jaywalk_crosses_the_road_and_ends_on_the_far_shoulder() -> None:
    """Băng qua đường là đi từ lề này sang lề kia, không phải dừng giữa làn xe chạy.

    Cách cũ lấy đích bằng ``-lane_offset``, ngầm giả định ego nằm giữa mặt cắt
    ngang. Đo trên anchor Town04 thì sai: hai lề ở ``lane_offset`` +1 và -2, nên
    người xuất phát ở lề +1 lại đi tới -1 — **giữa làn xe chạy**.
    """
    spec = make_spec(ManeuverType.JAYWALK)
    shoulders = get_template(spec.odd.road_type).shoulder_lane_offsets
    start = spec.actors[1].position.lane_offset

    root = ET.fromstring(convert_spec_to_xosc(spec))
    target = root.find(".//AcquirePositionAction/Position/RelativeLanePosition")
    assert target is not None
    # dLane đã nhân lane_sign, nên quy ngược về lane_offset để so với mặt cắt.
    lane_sign = 1 if get_template(spec.odd.road_type).ego_spawn.lane_id > 0 else -1
    destination = int(target.get("dLane")) * lane_sign

    assert destination in shoulders, "đích phải là lề đường"
    assert (destination > 0) != (start > 0), "đường đi phải cắt qua làn ego"


@pytest.mark.parametrize(
    ("weather", "expected_cloudiness"),
    [(Weather.CLEAR, 15.0), (Weather.RAIN, 65.0), (Weather.HEAVY_RAIN, 90.0), (Weather.FOG, 85.0)],
)
def test_cloud_cover_rides_on_sun_intensity_because_cloudstate_is_ignored(
    weather: Weather, expected_cloudiness: float
) -> None:
    """ScenarioRunner tính mây bằng `100 - Sun.intensity*100` và KHÔNG đọc `cloudState`.

    Bản trước hardcode `intensity="0.85"` cho mọi thời tiết, nên mây luôn 15% kể
    cả khi trời mưa — đo trên sc_023 ngày 23/08 ra cloudiness=15 với nắng 75 độ.
    Người xem nói "tôi không thấy trời mưa", và họ đúng: file khai báo mưa, CARLA
    có đổ mưa, nhưng dưới trời nắng gắt thì không ai nhận ra.
    """
    spec = make_spec(ManeuverType.CUT_IN)
    spec = spec.model_copy(update={"odd": spec.odd.model_copy(update={"weather": weather})})

    sun = ET.fromstring(convert_spec_to_xosc(spec)).find(".//Weather/Sun")
    assert sun is not None
    assert 100 - float(sun.get("intensity")) * 100 == pytest.approx(expected_cloudiness)


@pytest.mark.parametrize(
    ("time_of_day", "is_daylight"),
    [(TimeOfDay.DAY, True), (TimeOfDay.DUSK, True), (TimeOfDay.NIGHT, False)],
)
def test_night_scenarios_do_not_render_at_high_noon(time_of_day: TimeOfDay, is_daylight: bool) -> None:
    """Góc mặt trời phải theo thời điểm trong ngày, không phải hằng số.

    `dateTime` có đổi theo giờ nhưng ScenarioRunner chỉ dùng nó cho animation —
    góc mặt trời nó đọc thẳng từ `Sun@elevation`. Hardcode 1.31 rad thì kịch bản
    ban đêm cũng hiện ra giữa trưa nắng. CARLA hiểu góc âm là đêm.
    """
    spec = make_spec(ManeuverType.CUT_IN).model_copy(update={"time_of_day": time_of_day})

    sun = ET.fromstring(convert_spec_to_xosc(spec)).find(".//Weather/Sun")
    assert sun is not None
    assert (float(sun.get("elevation")) > 0) is is_daylight
